console.log("✅ uploads.js loaded");
const uploads = [
  { title: "Exterritorial", id: "10NEhLMhb0mACWJXVtQ-Inalpf0gNc2Ju" },
  { title: "Control Freak", id: "1mdd1G8RswZW3G_6gMT39O2h88HhXCrdn" },
  { title: "ARQ", id: "1KJ_R_RGVGwgpypYNEf-_2gJ6mDfCvLYH" },
  { title: "The Hunger Games", id: "1Agy9Z6IlEPwVqUK2VSDpBvpUFklBDOvp" },
  { title: "The Hunger Games: The Ballad of Songbirds and Snakes", id: "1XVaQPU0WOJiLWG23whj9jHMsCCCWpw4S" },
  { title: "Kill Command", id: "1wfsA6vF6Xyy10qR5EeOQHf7HEj1VtyOt" },
  { title: "Maze Runner: The Death Cure", id: "1kKzOIMcEq76IqmI4Z8AnV2gAkrDhAd15" },
  { title: "Morbius", id: "15ue4p4e14u7l_Bxhf5I2KH8BFAbAvi2C" },
  { title: "Shaun of the Dead", id: "1gqZ_IawXvSj-iQJB6L64kGFkbBg95lGO" },
  { title: "Smile 2", id: "1c4YOkoSiIKvM3ruYXRR2auFrT6hRmAKz" },
  { title: "Smile", id: "1DDijEmLwM7tqjaQdrpwGzgtjSW0Sws8F" },
  { title: "Sting", id: "1IKJK2TM13u64knIpX749GIbkxiQxxbzT" },
  { title: "The Dark Tower", id: "1RSaJWvJM4QjNG99iTDI4nhuqTHIO1GMz" },
  { title: "The Mist", id: "1RIBLkQ6QpsUvIeCBZXq9cBG-pIkn5_h-" },
  { title: "A Working Man", id: "1SzBfgO_0lRYF9IYWFdUWWfARdwNrdUKX" },
  { title: "Final Destination Bloodlines", id: "1WW5wVra8gjiEaKzVy54SOwxLiRWq2zGs" },
  { title: "Kraken", id: "10plK6C0pCWeITPOtII_nLfZCYrRAhRdB" },
  { title: "Echo Valley", id: "1LG2tPchnG6K8nwCIKAiafkIw2WxUGQLR" },
  { title: "How to Train Your Dragon", id: "1piyv0TgMOghCPGVE2Wq3KLKoUrIKv0Z2" },
  { title: "Predator: Killer of Killers", id: "1TtTXWUWA7Q2DUSNIa2vzTI-Ko9xevg0B" },
  { title: "Sneaks", id: "1JXM98DsuYU3Sp8I7PWQB2DKxCfvRjrIm" },
  { title: "Warfare", id: "1MMVOlPB6hSM7YWaVdZH8ZaphgBcuNjxb" },
  { title: "Deep Cover", id: "1FkWF1R_8aF4FvjJe0I7c5BsruZMMuqS0" },
  { title: "The Amateur", id: "1VTTrOwGXgleyx5HG6zjqMpCRYQ3Xu_eP" },
  { title: "K.O.", id: "1mI1iZeSxWTDAlrHkERhM7f7bd2wX3fx_" },
  { title: "Black Panther", id: "1wQzxwyEYz7sCvLmQw9vtnfm6H930V1PA" },
  { title: "Venom", id: "1UPZMNDrpJUytSkRJknwTLeyUDC4l6yrG" },
  { title: "Avengers: Endgame", id: "1b7Shy_iaVrltNtc7SwlZUiHETiUC_04E" },
  { title: "The Accountant 2", id: "1HFLyYJrz13ToC2qJNWmV095p03hhpCqO" },
  { title: "KPop Demon Hunters", id: "1xPWoVGGBPxntrUDG-aJ5xs0RHWF5ciQR" },
  { title: "The Phoenician Scheme", id: "1lNW4NObORgWmj8m8nO7EWc0UwcgLjp6j" },
  { title: "Mountainhead", id: "1Sca89zFpdZ_Xdq0OJ212hGvqE4u2sDv7" },
  { title: "A Minecraft Movie", id: "1j18M-eRtoF6hg2GX-cQczaJpXDfCQwaR" },
  { title: "Shadow Force", id: "1PVZlgl1s8_POQSeG1wFyjU8quZRiDvb9" },
  { title: "Sinners", id: "1kfegH8wXxO3MYbXu8ZBv_7dRFSc5Yvax" },
  { title: "Diablo", id: "1nwtSJKFK9a47g0CnCMIu8EMbSEXLhIrF" },
  { title: "Red Land", id: "1V9zBN6XruePOanqnpXLg8bUyH5Z8BjkE" },
  { title: "From the World of John Wick: Ballerina", id: "1vzP_bGwBQxMiNwagdYBXlGQNScd-yYON" },
  { title: "Ice Road: Vengeance", id: "1YnPIulaX95A8d9l7E9iFL_bQgxZwhQM9" },
  { title: "Thunderbolts*", id: "1SJAlHbq2cWtBYMNKydSNsDBC4cto_jOM" }
];
