const uploads = [
  { title: "Exterritorial", id: "10NEhLMhb0mACWJXVtQ-Inalpf0gNc2Ju", downloadLink: "https://drive.google.com/u/0/uc?id=10NEhLMhb0mACWJXVtQ-Inalpf0gNc2Ju&export=download" },
  { title: "Control Freak", id: "1mdd1G8RswZW3G_6gMT39O2h88HhXCrdn", downloadLink: "https://drive.google.com/u/0/uc?id=1mdd1G8RswZW3G_6gMT39O2h88HhXCrdn&export=download" },
  { title: "ARQ", id: "1KJ_R_RGVGwgpypYNEf-_2gJ6mDfCvLYH", downloadLink: "https://drive.google.com/u/0/uc?id=1KJ_R_RGVGwgpypYNEf-_2gJ6mDfCvLYH&export=download" },
  { title: "The Hunger Games", id: "1Agy9Z6IlEPwVqUK2VSDpBvpUFklBDOvp", downloadLink: "https://drive.google.com/u/0/uc?id=1Agy9Z6IlEPwVqUK2VSDpBvpUFklBDOvp&export=download" },
  { title: "The Hunger Games: The Ballad of Songbirds and Snakes", id: "1XVaQPU0WOJiLWG23whj9jHMsCCCWpw4S", downloadLink: "https://drive.google.com/u/0/uc?id=1XVaQPU0WOJiLWG23whj9jHMsCCCWpw4S&export=download" },
  { title: "Kill Command", id: "1wfsA6vF6Xyy10qR5EeOQHf7HEj1VtyOt", downloadLink: "https://drive.google.com/u/0/uc?id=1wfsA6vF6Xyy10qR5EeOQHf7HEj1VtyOt&export=download" },
  { title: "Maze Runner: The Death Cure", id: "1kKzOIMcEq76IqmI4Z8AnV2gAkrDhAd15", downloadLink: "https://drive.google.com/u/0/uc?id=1kKzOIMcEq76IqmI4Z8AnV2gAkrDhAd15&export=download" },
  { title: "Morbius", id: "15ue4p4e14u7l_Bxhf5I2KH8BFAbAvi2C", downloadLink: "https://drive.google.com/u/0/uc?id=15ue4p4e14u7l_Bxhf5I2KH8BFAbAvi2C&export=download" },
  { title: "Shaun of the Dead", id: "1gqZ_IawXvSj-iQJB6L64kGFkbBg95lGO", downloadLink: "https://drive.google.com/u/0/uc?id=1gqZ_IawXvSj-iQJB6L64kGFkbBg95lGO&export=download" },
  { title: "Smile 2", id: "1c4YOkoSiIKvM3ruYXRR2auFrT6hRmAKz", downloadLink: "https://drive.google.com/u/0/uc?id=1c4YOkoSiIKvM3ruYXRR2auFrT6hRmAKz&export=download" },
  { title: "Smile", id: "1DDijEmLwM7tqjaQdrpwGzgtjSW0Sws8F", downloadLink: "https://drive.google.com/u/0/uc?id=1DDijEmLwM7tqjaQdrpwGzgtjSW0Sws8F&export=download" },
  { title: "Sting", id: "1IKJK2TM13u64knIpX749GIbkxiQxxbzT", downloadLink: "https://drive.google.com/u/0/uc?id=1IKJK2TM13u64knIpX749GIbkxiQxxbzT&export=download" },
  { title: "The Dark Tower", id: "1RSaJWvJM4QjNG99iTDI4nhuqTHIO1GMz", downloadLink: "https://drive.google.com/u/0/uc?id=1RSaJWvJM4QjNG99iTDI4nhuqTHIO1GMz&export=download" },
  { title: "The Mist", id: "1RIBLkQ6QpsUvIeCBZXq9cBG-pIkn5_h-", downloadLink: "https://drive.google.com/u/0/uc?id=1RIBLkQ6QpsUvIeCBZXq9cBG-pIkn5_h-&export=download" },
  { title: "A Working Man", id: "1SzBfgO_0lRYF9IYWFdUWWfARdwNrdUKX", downloadLink: "https://drive.google.com/u/0/uc?id=1SzBfgO_0lRYF9IYWFdUWWfARdwNrdUKX&export=download" },
  { title: "Final Destination Bloodlines", id: "1WW5wVra8gjiEaKzVy54SOwxLiRWq2zGs", downloadLink: "https://drive.google.com/u/0/uc?id=1WW5wVra8gjiEaKzVy54SOwxLiRWq2zGs&export=download" },
  { title: "Kraken", id: "10plK6C0pCWeITPOtII_nLfZCYrRAhRdB", downloadLink: "https://drive.google.com/u/0/uc?id=10plK6C0pCWeITPOtII_nLfZCYrRAhRdB&export=download" },
  { title: "Echo Valley", id: "1LG2tPchnG6K8nwCIKAiafkIw2WxUGQLR", downloadLink: "https://drive.google.com/u/0/uc?id=1LG2tPchnG6K8nwCIKAiafkIw2WxUGQLR&export=download" },
  { title: "How to Train Your Dragon", id: "1piyv0TgMOghCPGVE2Wq3KLKoUrIKv0Z2", downloadLink: "https://drive.google.com/u/0/uc?id=1piyv0TgMOghCPGVE2Wq3KLKoUrIKv0Z2&export=download" },
  { title: "Predator: Killer of Killers", id: "1TtTXWUWA7Q2DUSNIa2vzTI-Ko9xevg0B", downloadLink: "https://drive.google.com/u/0/uc?id=1TtTXWUWA7Q2DUSNIa2vzTI-Ko9xevg0B&export=download" },
  { title: "Sneaks", id: "1JXM98DsuYU3Sp8I7PWQB2DKxCfvRjrIm", downloadLink: "https://drive.google.com/u/0/uc?id=1JXM98DsuYU3Sp8I7PWQB2DKxCfvRjrIm&export=download" },
  { title: "Warfare", id: "1MMVOlPB6hSM7YWaVdZH8ZaphgBcuNjxb", downloadLink: "https://drive.google.com/u/0/uc?id=1MMVOlPB6hSM7YWaVdZH8ZaphgBcuNjxb&export=download" },
  { title: "Deep Cover", id: "1FkWF1R_8aF4FvjJe0I7c5BsruZMMuqS0", downloadLink: "https://drive.google.com/u/0/uc?id=1FkWF1R_8aF4FvjJe0I7c5BsruZMMuqS0&export=download" },
  { title: "The Amateur", id: "1VTTrOwGXgleyx5HG6zjqMpCRYQ3Xu_eP", downloadLink: "https://drive.google.com/u/0/uc?id=1VTTrOwGXgleyx5HG6zjqMpCRYQ3Xu_eP&export=download" },
  { title: "K.O.", id: "1mI1iZeSxWTDAlrHkERhM7f7bd2wX3fx_", downloadLink: "https://drive.google.com/u/0/uc?id=1mI1iZeSxWTDAlrHkERhM7f7bd2wX3fx_&export=download" },
  { title: "Black Panther", id: "1wQzxwyEYz7sCvLmQw9vtnfm6H930V1PA", downloadLink: "https://drive.google.com/u/0/uc?id=1wQzxwyEYz7sCvLmQw9vtnfm6H930V1PA&export=download" },
  { title: "Venom", id: "1UPZMNDrpJUytSkRJknwTLeyUDC4l6yrG", downloadLink: "https://drive.google.com/u/0/uc?id=1UPZMNDrpJUytSkRJknwTLeyUDC4l6yrG&export=download" },
  { title: "Avengers: Endgame", id: "1b7Shy_iaVrltNtc7SwlZUiHETiUC_04E", downloadLink: "https://drive.google.com/u/0/uc?id=1b7Shy_iaVrltNtc7SwlZUiHETiUC_04E&export=download" },
  { title: "The Accountant 2", id: "1HFLyYJrz13ToC2qJNWmV095p03hhpCqO", downloadLink: "https://drive.google.com/u/0/uc?id=1HFLyYJrz13ToC2qJNWmV095p03hhpCqO&export=download" },
  { title: "KPop Demon Hunters", id: "1xPWoVGGBPxntrUDG-aJ5xs0RHWF5ciQR", downloadLink: "https://drive.google.com/u/0/uc?id=1xPWoVGGBPxntrUDG-aJ5xs0RHWF5ciQR&export=download" },
  { title: "The Phoenician Scheme", id: "1lNW4NObORgWmj8m8nO7EWc0UwcgLjp6j", downloadLink: "https://drive.google.com/u/0/uc?id=1lNW4NObORgWmj8m8nO7EWc0UwcgLjp6j&export=download" },
  { title: "Mountainhead", id: "1Sca89zFpdZ_Xdq0OJ212hGvqE4u2sDv7", downloadLink: "https://drive.google.com/u/0/uc?id=1Sca89zFpdZ_Xdq0OJ212hGvqE4u2sDv7&export=download" },
  { title: "A Minecraft Movie", id: "1j18M-eRtoF6hg2GX-cQczaJpXDfCQwaR", downloadLink: "https://drive.google.com/u/0/uc?id=1j18M-eRtoF6hg2GX-cQczaJpXDfCQwaR&export=download" },
  { title: "Shadow Force", id: "1PVZlgl1s8_POQSeG1wFyjU8quZRiDvb9", downloadLink: "https://drive.google.com/u/0/uc?id=1PVZlgl1s8_POQSeG1wFyjU8quZRiDvb9&export=download" },
  { title: "Sinners", id: "1kfegH8wXxO3MYbXu8ZBv_7dRFSc5Yvax", downloadLink: "https://drive.google.com/u/0/uc?id=1kfegH8wXxO3MYbXu8ZBv_7dRFSc5Yvax&export=download" },
  { title: "Diablo", id: "1nwtSJKFK9a47g0CnCMIu8EMbSEXLhIrF", downloadLink: "https://drive.google.com/u/0/uc?id=1nwtSJKFK9a47g0CnCMIu8EMbSEXLhIrF&export=download" },
  { title: "Red Land", id: "1V9zBN6XruePOanqnpXLg8bUyH5Z8BjkE", downloadLink: "https://drive.google.com/u/0/uc?id=1V9zBN6XruePOanqnpXLg8bUyH5Z8BjkE&export=download" },
  { title: "From the World of John Wick: Ballerina", id: "1vzP_bGwBQxMiNwagdYBXlGQNScd-yYON", downloadLink: "https://drive.google.com/u/0/uc?id=1vzP_bGwBQxMiNwagdYBXlGQNScd-yYON&export=download" },
  { title: "Ice Road: Vengeance", id: "1YnPIulaX95A8d9l7E9iFL_bQgxZwhQM9", downloadLink: "https://drive.google.com/u/0/uc?id=1YnPIulaX95A8d9l7E9iFL_bQgxZwhQM9&export=download" },
  { title: "Thunderbolts*", id: "1SJAlHbq2cWtBYMNKydSNsDBC4cto_jOM", downloadLink: "https://drive.google.com/u/0/uc?id=1SJAlHbq2cWtBYMNKydSNsDBC4cto_jOM&export=download" }
];
